name: blui-labels
run-name: Labels
on: 
  pull_request_target:
    types:
      - opened
  workflow_call:

permissions:
  pull-requests: write

jobs:
  label-master:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'master' }}
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['master', 'brightlayer-ui']
            })

  label-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'dev' }}
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['brightlayer-ui']
            })