name: Tagging

env:
  GH_TOKEN: ${{ github.token }}
  CURRENT_BRANCH: ${{ github.ref_name }}

on:
  push:
    branches:
      - master

jobs:
  tag-publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd blui-publish && yarn tag:package -b ${CURRENT_BRANCH} -s -blui-publish
  tag-tag-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd blui-tag && yarn tag:package -b ${CURRENT_BRANCH} -s -blui-tag
      
